#
# Makefile for the sysfs virtual filesystem
#

# FUJITSU:2011-05-27 Mod start
obj-y       := inode.o file.o dir.o symlink.o mount.o bin.o \
           group.o sphinx_gb.o
# FUJITSU:2011-05-27 Mod end
