#
# Makefile for fujitsu devices that really don't fit anywhere else.
#

obj-y += fcsmd/
obj-y += fcfd/
obj-y += compass/
obj-y += i2cuart/
obj-y += walkmotion/
obj-y += pipe/
obj-y += irda/
obj-y += memread/
obj-y += proximity/
obj-y += light/
obj-y += sd/
obj-y += ftdtv_drv/
obj-y += touchscreen/
obj-y += keypad/
obj-y += irremo/
obj-y += stschk/
